inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "tmp/**/*"
    - "config/initializers/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "bin/*"
    - "app/helpers/devise_helper.rb"
  DisplayCopNames: true
  TargetRubyVersion: 2.7.1

AsciiComments:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false

AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

AndOr:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/environments/development.rb'

Metrics/AbcSize:
  Max: 60

Style/FrozenStringLiteralComment:
  Enabled: false
