version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec puma -C config/puma.rb
    tty: true
    stdin_open: true
    volumes:
      - .:/sample_app
      - public_data:/sample_app/public
      - tmp_data:/sample_app/tmp
      - log_data:/sample_app/log
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - public_data:/sample_app/public
      - tmp_data:/sample_app/tmp
    depends_on:
      - web

volumes:
  db_data:
  public_data:
  tmp_data:
  log_data:
